### PR TITLE
Remove overloading of 0 arg zip()

### LINKED ISSUE #621: DataStructures.jl pirates zip()
```
julia> zip()
zip()

julia> using DataStructures

julia> zip()
ERROR: ArgumentError: collection must be non-empty
Stacktrace:
 [1] _findmin(::Tuple{}, ::Colon) at ./array.jl:2201
 [2] findmin(::Tuple{}) at ./array.jl:2195
 [3] DataStructures.ZippedSparseIntSetIterator(; exclude::Tuple{}) at /home/takafumi/.julia/dev/DataStructures/src/sparse_int_set.jl:208
 [4] DataStructures.ZippedSparseIntSetIterator() at /home/takafumi/.julia/dev/DataStructures/src/sparse_int_set.jl:208
 [5] zip(; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/takafumi/.julia/dev/DataStructures/src/sparse_int_set.jl:213
 [6] zip() at /home/takafumi/.julia/dev/DataStructures/src/sparse_int_set.jl:213
 [7] top-level scope at REPL[4]:1

(tmp_y5_3d7e.julia_tmp) pkg> st
Status `/tmp/tmp_y5_3d7e.julia_tmp/Project.toml`
  [864edb3b] DataStructures v0.17.15 `~/.julia/dev/DataStructures`
  [44cfe95a] Pkg
```

### PR DESCRIPTION
**Pull request by tkf**
close #621

### CODE REVIEW

File: src/sparse_int_set.jl [hunk 1]
```diff
@@ -210,7 +210,8 @@ struct ZippedSparseIntSetIterator{VT,IT}
     end
 end
 
-Base.zip(s::SparseIntSet...;kwargs...) = ZippedSparseIntSetIterator(s...;kwargs...)
+Base.zip(s0::SparseIntSet, s::SparseIntSet...; kwargs...) =
+    ZippedSparseIntSetIterator(s0, s...; kwargs...)
```
Comment (oxinabox) [inline src/sparse_int_set.jl:214]: If we are doing multiline we should do multipline

```suggestion
function Base.zip(s0::SparseIntSet, s::SparseIntSet...; kwargs...)
    return ZippedSparseIntSetIterator(s0, s...; kwargs...)
end
```

we do need to officially adopt a style guide #539

**Comment by oxinabox** [comment]
Approved as concept all seems right, but got to workout what is up with CI and do other few small things before merging

**Comment by tkf** [comment]
Not sure if `need version bump` is a reminder or a request to be done within this patch but I just go ahead and bump the number. Let me know if you want to revert it (or you can just do it and merge).
